version: "3"
services:
  adminer:
    image: adminer
    restart: always
    container_name: blazing-fast-search-engine-adminer
    ports: 
      - 8089:8080
    links:
      - db
  db:
    image: postgres
    container_name: blazing-fast-search-engine-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
      POSTGRES_DB: postgres

